/*
 * Stoatworks Labs - About window data for Tilter.
 *
 * NORMALLY GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json. This copy was hand-written when the repo was
 * started, because tilter is not in projects.json yet. Re-run the sync once
 * the website page exists and let it overwrite this file.
 *
 * `guide` and `page` are deliberately EMPTY. StoatworksAboutParams.h leaves a
 * link out of the button list when its URL is empty, which is the whole point:
 * a button that opens a 404 is worse than no button. Fill them in when the
 * pages are live -- the sync does it, and the About block grows by two buttons
 * on its own.
 *
 * `version` here is a fallback. The build injects the real one and overrides
 * it.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Tilter";
    inline constexpr auto slug = "tilter";
    inline constexpr auto hook = "Tilt-shift lens for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/tilter";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
